name: Deploy to Heroku

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14 # 안정적인 Heroku 배포 액션 사용
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
          docker_heroku_process_type: web
          stack: "heroku-24"
          
      - name: Set Heroku Config Vars
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          HD_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          HD_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          HD_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          HD_S3_BUCKET: ${{ secrets.S3_BUCKET }}
